### ISSUE TITLE
[Bug] InvalidSignature in oid4vc-manager since identity wallet 0.7.2

### ISSUE THREAD

**Issue by chriamue** [impierce/siopv2#81]
### Description

Since I updated the Identity Wallet (5. Nov, V 0.7.2) (6. Nov, V 0.7.3)
issuing a certificate results in a InvalidSignature.
Since I didn't change the server, what changed in the Wallet, so it results in this error?
[konnektoren_certificate.json](https://github.com/user-attachments/files/17668822/konnektoren_certificate.json)
Maybe something needs to be updated in CredentialIssuerMetadata
https://github.com/konnektoren/konnektoren-vc/blob/c00411b413f0d22b8a9203f929a4bcfd7fb6e6dd/src/manager/custom_credential_issuer.rs#L42 ?

### Hardware Specification

Operating system: Docker rust:bookworm
```
oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature
```
Before, the V0.6

### Steps to Reproduce the Bug

1. Scan QR code on https://konnektoren.help/profile
2. Select "Konnektoren Certificate" in the UniMe Wallet
3. click Accept credentials button

### Expected Behaviour

Credential should be issued to Identity Wallet (UniMe).

### Actual Behaviour

The wallet shows ```Oops! Something goes wrong ...```
The server side errors:
```server-1  | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/openid4vc-3cfffdf417831466/401f54e/oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature```

### Errors

```shell
server-1  | 2024-11-07T19:42:05.251266Z DEBUG hyper::proto::h1::io: parsed 25 headers
server-1  | 2024-11-07T19:42:05.251290Z DEBUG hyper::proto::h1::conn: incoming body is content-length (415 bytes)
server-1  | 2024-11-07T19:42:05.251318Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | 2024-11-07T19:42:05.251432Z DEBUG konnektoren_vc::storage::memory_storage: get_authorization_code 0a19ea2a-8d4d-4444-ab3f-3958d00a5e36    
server-1  | 2024-11-07T19:42:05.251489Z  INFO konnektoren_vc::storage::memory_storage: Storing certificate with id: 341e678b-d449-4fa9-af52-3e3abfa03256    
server-1  | 2024-11-07T19:42:05.251495Z  INFO konnektoren_vc::storage::memory_storage: Associating pre-authorized code O3KmALhjEJWc0kXy with certificate id: 341e678b-d449-4fa9-af52-3e3abfa03256    
server-1  | 2024-11-07T19:42:05.251558Z DEBUG hyper::proto::h1::io: flushed 674 bytes
server-1  | 2024-11-07T19:42:09.057818Z DEBUG hyper::proto::h1::io: parsed 12 headers
server-1  | 2024-11-07T19:42:09.057841Z DEBUG hyper::proto::h1::conn: incoming body is empty
server-1  | 2024-11-07T19:42:09.058075Z DEBUG hyper::proto::h1::io: flushed 2002 bytes
server-1  | 2024-11-07T19:42:10.870986Z DEBUG hyper::proto::h1::io: parsed 12 headers
server-1  | 2024-11-07T19:42:10.871006Z DEBUG hyper::proto::h1::conn: incoming body is empty
server-1  | 2024-11-07T19:42:10.871174Z DEBUG hyper::proto::h1::io: flushed 444 bytes
server-1  | 2024-11-07T19:42:11.183896Z DEBUG hyper::proto::h1::io: parsed 12 headers
server-1  | 2024-11-07T19:42:11.183916Z DEBUG hyper::proto::h1::conn: incoming body is empty
server-1  | 2024-11-07T19:42:11.184095Z DEBUG hyper::proto::h1::io: flushed 2002 bytes
server-1  | 2024-11-07T19:42:11.278739Z DEBUG hyper::proto::h1::io: parsed 14 headers
server-1  | 2024-11-07T19:42:11.278754Z DEBUG hyper::proto::h1::conn: incoming body is content-length (110 bytes)
server-1  | 2024-11-07T19:42:11.278778Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | 2024-11-07T19:42:11.278859Z DEBUG konnektoren_vc::storage::memory_storage: get_token_response: PreAuthorizedCode { pre_authorized_code: "O3KmALhjEJWc0kXy", tx_code: None }    
server-1  | 2024-11-07T19:42:11.278870Z  INFO konnektoren_vc::storage::memory_storage: Associating access token zxROrdaOINvW4FLb with certificate id: 341e678b-d449-4fa9-af52-3e3abfa03256    
server-1  | 2024-11-07T19:42:11.278919Z DEBUG hyper::proto::h1::io: flushed 381 bytes
server-1  | 2024-11-07T19:42:11.373384Z DEBUG hyper::proto::h1::io: parsed 15 headers
server-1  | 2024-11-07T19:42:11.373401Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1365 bytes)
server-1  | 2024-11-07T19:42:11.373426Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/openid4vc-3cfffdf417831466/401f54e/oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature
server-1  | 2024-11-07T19:42:11.915941Z DEBUG hyper::proto::h1::io: parsed 15 headers
server-1  | 2024-11-07T19:42:11.915958Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1365 bytes)
server-1  | 2024-11-07T19:42:11.915982Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/openid4vc-3cfffdf417831466/401f54e/oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature
server-1  | 2024-11-07T19:42:12.767720Z DEBUG hyper::proto::h1::io: parsed 15 headers
server-1  | 2024-11-07T19:42:12.767739Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1365 bytes)
server-1  | 2024-11-07T19:42:12.767766Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/openid4vc-3cfffdf417831466/401f54e/oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature
server-1  | 2024-11-07T19:42:16.045471Z DEBUG hyper::proto::h1::io: parsed 15 headers
server-1  | 2024-11-07T19:42:16.045486Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1365 bytes)
server-1  | 2024-11-07T19:42:16.045510Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/openid4vc-3cfffdf417831466/401f54e/oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature
server-1  | 2024-11-07T19:42:18.115234Z DEBUG hyper::proto::h1::io: parsed 15 headers
server-1  | 2024-11-07T19:42:18.115250Z DEBUG hyper::proto::h1::conn: incoming body is content-length (1365 bytes)
server-1  | 2024-11-07T19:42:18.115274Z DEBUG hyper::proto::h1::conn: incoming body completed
server-1  | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/openid4vc-3cfffdf417831466/401f54e/oid4vc-manager/src/servers/credential_issuer.rs:184:10:
server-1  | called `Result::unwrap()` on an `Err` value: InvalidSignature
```

**Comment by chriamue** [comment]
Problem does not exist anymore with UniMe Wallet Version 0.7.4 (16. Dec 2024).
I did not change the Backend.

Thank you for this Project.
